name: ${project.name}
main: net.azisaba.changeresourcepack.ChangeResourcePack
version: ${project.version}
author: YukiLeafX
description: ${project.description}
website: ${project.url}
commands:
  changepack:
    description: サーバーリソースパックを変更します
    permission: changeresourcepack.command.changepack
    usage: "§c使用法: /changepack <URL> [ハッシュ値]"
permissions:
  changeresourcepack.command.changepack:
    default: op
